# Generated by Django 5.1.5 on 2025-01-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='activo',
            new_name='estado',
        ),
    ]
