# Generated by Django 5.1.5 on 2025-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_activo_empleado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('Empresa', 'Empresa'), ('Individuo', 'Individuo')], max_length=10),
        ),
    ]
