# Generated by Django 5.1.5 on 2025-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='lugarVenta',
            field=models.CharField(default='Capital', max_length=30),
        ),
    ]
