# Generated by Django 5.1.5 on 2025-01-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_lugarventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='formaDePago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=15),
        ),
    ]
