# Generated by Django 5.1.5 on 2025-01-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('productos', '0003_materiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Material', 'Compra de Material'), ('Salario', 'Pago de Salario')], max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formaDePago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=15)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastoProveedor', to='personal.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesGastosMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleMateriales', to='productos.materiales')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleGastoMaterial', to='gastos.gastomaterial')),
            ],
        ),
        migrations.CreateModel(
            name='GastoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Material', 'Compra de Material'), ('Salario', 'Pago de Salario')], max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formaDePago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastoSalario', to='personal.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
